### ISSUE TITLE
SMV-AV: Compile win32kfull and smb2 modules for AV

### ISSUE THREAD

**Issue by shuvendu-lahiri** [microsoft/Static-Module-Verifier#12]
Currently win32kfull bpl does not include most interesting parts of source code.

SMB2 fails due to first .src files and then ESP failure.

**Comment by rahulku** [comment]
I believe this is fixed now. Can you confirm?

**Comment by shuvendu-lahiri** [comment]
Unfortunately, I have not been able to compile win32kfull (bcz on this module on my enlistment). Will retry in a few days, and open if bcz passes but smv fails
