### ISSUE TITLE
Feature request: Is it possible to get a global break on error flag? 

### ISSUE THREAD

**Issue by jakoblichtenberg** [microsoft/Static-Module-Verifier#2]
As discussed 2016/11/18:

1) BreakOnError should be default.

2) It is reasonable that essentially all levels of the XML file can override this default behavior.  On a per configuration, per action and per command.

**Comment by jakoblichtenberg** [comment]
As discussed 2016/11/18:

1) BreakOnError should be default.

2) It is reasonable that essentially all levels of the XML file can override this default behavior.  On a per configuration, per action and per command.

**Comment by rahulku** [comment]
By default, breakOnError is set to true for actions. There is a different issue that was interfering with the breakOnError working correctly. That should be fixed shortly. 

Based on that fix, I think it is perfectly fine if we enable users to set it to false, currently only at an action level. In the future, we can do this for a command as well.

**Comment by jakoblichtenberg** [comment]
I agree!
