### ISSUE TITLE
SMV Cloud: SMV saw an error yet still return error code 0

### ISSUE THREAD

**Issue by jakoblichtenberg** [microsoft/Static-Module-Verifier#21]
Hi Rahul.

I ran two PTPs on two separate machines.  On both machines I see sporadic examples of errors from the Azure layer yet SMV returns 0 indicating a succesful run.

Fix suggested is trivial: Change regular error to a "Fatal error".  Or at least make sure an error results in a non-zero exit code from SMV.

Here is a specific example: 
+++
robocopy /mir /nfl /ndl C:\slam1\WDK\src_5239\fail_drivers\kmdf\fail_driver3\driver \\redmond\osg\Threshold\Tools\CORE\SiGMa\DPlat-DQT\Share\JakobL\Public\2017-04-10-smv_fatalerror_as_nonfatal
+++

Notice in svb.log you see:
+++
  [INFO] 23 of 347 jobs remaining. Avg(s): 8.65. Std.Dev(s): 13.76[ERROR] Failed to complete action: 0a88c33f-6e33-4c7f-bd5c-c0debd6a2b1b (CheckRule)
...
jrerun final errorlevel 0 after 1 attempt(s).
+++

How often does this happen? In average 9.5 times per PTP.
+++
From jakobl1:
C:\slam1\WDK>findstr /m /s /c:"[ERROR] Failed to complete action" svb.log
src_5239\fail_drivers\kmdf\fail_driver3\driver\svb.log
src_5239\kmdf\fakemodem\svb.log
src_6001\input\mouser\svb.log
src_7600\storage\class\cdrom\svb.log
src_ndis\sdvmp_fail_09\svb.log
win8_rtm\drivers\wdm\1394\protocol\avc\svb.log
win8_rtm\drivers\wdm\usb\usb3\ucx\sys\driver\svb.log
win8_rtm\minkernel\storage\sbp2port\svb.log
win8_rtm\net\rras\ndis\ndproxy\svb.log
+++
From jakobl3:
K:\SD\slam\2\WDK>findstr /m /s /c:"[ERROR] Failed to complete action" svb.log
src_5239\kmdf\AMCC5933\sys\AMCC5933ISA\svb.log
src_5239\kmdf\nonpnp_fail4\svb.log
src_7600\storage\class\cdrom\svb.log
src_ndis\sdvmp_fail_30c\svb.log
src_storport\StorportMiniports\storahci\svb.log
win8_rtm\drivers\wdm\1394\protocol\avc\svb.log
win8_rtm\drivers\wdm\ir\circlass\svb.log
win8_rtm\minkernel\storage\sbp2port\svb.log
win8_rtm\net\unimodem\src\sys\modem\svb.log
win8_rtm\printscan\imaging\kernel\usbscan\winnt\svb.log
+++

**Comment by rahulku** [comment]
fixed with 02167f8b5cc25fe007ff41a3040f55007e21d811
