### ISSUE TITLE
SMV-SDV: Provide wlimit style protection of all started processes

### ISSUE THREAD

**Issue by jakoblichtenberg** [microsoft/Static-Module-Verifier#8]
This is a large feature request.  It would however be a strong foundational improvement to SMV.

What:
1) Wrap all processes in a job.  
2) By default prevent processes "escaping".  
3) Provide knobs to control limits on various resources: wall clock time, space, user time.  Knobs would be accessible thru xml tags I would imagine.
4) Provide resource statistics upon job completion.

When:
For build, intercepted build and verification.  Really any calls to "exec".

How:
I would be open to expose a wlimit API as a managed dll.  This dll would essentially provide a replacement of "exec".  Next step would be to call this from SMV and additionally expose the most useful knobs as XML.

**Comment by rahulku** [comment]
implemented and available in SMV now.
